### ISSUE TITLE
Rename bookmarks

### ISSUE THREAD

**Issue by raffaelemancuso** [h-hg/yamb.yazi#1]
Can we have a keybinding to rename bookmarks, for example ur and uR?

**Comment by h-hg** [comment]
There's no direct renaming feature at the moment. You can use keybinding ua for the path you want to rename. I'll implement it later.

**Comment by h-hg** [comment]
Thanks for the suggestion. This feature has already been implemented. Have a pleasant experience.

**Comment by raffaelemancuso** [comment]
Thanks
