### ISSUE TITLE
Desktop bookmark automatically created

### ISSUE THREAD

**Issue by bertradio** [h-hg/yamb.yazi#4]
I don't want a bookmark for Desktop. But even after I delete it, it is re-created with the key d when I exit and there seems to be no way to prevent this.

**Comment by h-hg** [comment]
Can you show your `init.lua`?

**Comment by bertradio** [comment]
I found the issue, it was code in my init.lua for yazi which set the bookmark. I had copied it from your site.

**Comment by doorbuster** [comment]
Ok to ask a question in a closed issue?  I also found the code that's setting the desktop bookmark, but I'm not a lua coder and can't figure out which parts of the code to remove.  Everything I've tried results in loss of function of the plugin.  I'm on EndeavourOS.  Thanks for a bit more specifics.  :)

**Comment by h-hg** [comment]
> Ok to ask a question in a closed issue? I also found the code that's setting the desktop bookmark, but I'm not a lua coder and can't figure out which parts of the code to remove. Everything I've tried results in loss of function of the plugin. I'm on EndeavourOS. Thanks for a bit more specifics. :)

Just
```lua
require("yamb"):setup {
}
```
